name: Test (PR)

on: [pull_request]
env:
  BUILD: false
jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [macos-latest]
        include:
          - build: macos-latest
            os: macos-latest
            rust: stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup environment
        run: |
          chmod +x ci/buildvars.sh
          ci/buildvars.sh

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
        if: env.BUILD == 'true'
      - name: Run Tests
        run: |
          git fetch --unshallow
          rustup target add aarch64-apple-darwin
          sudo xcode-select -s "/Applications/Xcode_12.2.app"
          export SDKROOT=$(xcrun -sdk macosx11.0 --show-sdk-path)
          export MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.0 --show-sdk-platform-version)

          git checkout 11e0cf842628685036265a6164295dd18d543978
          CARGO_INCREMENTAL=1 cargo build -v --target aarch64-apple-darwin

          git checkout e9662ef8b6da853a58253ffb71c8be28f295482d
          CARGO_INCREMENTAL=1 cargo build -v --target aarch64-apple-darwin
        env:
          RUST_BACKTRACE: 1
